services:
  log-source:
    build: ./log-source
    volumes:
      - ./data:/data
    depends_on:
      - preprocessor

  preprocessor:
    build: ./preprocessor
    ports:
      - "5000:5000"
    depends_on:
      - detector

  detector:
    build: ./detector
    ports:
      - "6000:6000"
    volumes:
      - ./models:/models
    depends_on:
      - visualizer

  visualizer:
    build: ./visualizer
    ports:
      - "8501:8501"