services:
  log-source:
    build: ./log-source
    volumes:
      - ./data:/data
    depends_on:
      - preprocessor
    networks:
      - aiops-net

  preprocessor:
    build: ./preprocessor
    ports:
      - "5001:5001"
    volumes:
      - ./models:/models
    depends_on:
      - detector
    networks:
      - aiops-net

  detector:
    build: ./detector
    depends_on:
      - visualizer-api
    volumes:
      - ./models:/models
    networks:
      - aiops-net

  visualizer-api:
    build: ./visualizer-api
    ports:
      - "8502:8502"
    volumes:
      - ./data:/data
    networks:
      - aiops-net

  visualizer-ui:
    build: ./visualizer-ui
    ports:
      - "8501:8501"
    volumes:
      - ./data:/data
    depends_on:
      - visualizer-api
    networks:
      - aiops-net

networks:
  aiops-net:
    driver: bridge