apiVersion: v1
kind: ConfigMap
metadata:
  name: anomaly-detector-config
  namespace: default
data:
  # Log Collector 설정
  LOG_FILE: "/data/HDFS_2k.log"
  BATCH_SIZE: "5"
  DELAY: "1.0"

  # Detector 설정
  MAX_SEQUENCE_LENGTH: "50"
  MODEL_TYPE: "gru"
